sudo wget -O /var/www/html/b.txt https://raw.githubusercontent.com/joshdick/miniProxy/master/miniProxy.php
sudo sed -i s/miniProxy/webGATE/g /var/www/html/b.txt
sudo sed -i s/example.net/www.google.com/ /var/www/html/b.txt
sudo sed -ir 's/<.*r \/>/<center>/' /var/www/html/b.txt
sudo sed -ir 's/ size.*>/\/><\/form><\/center>/' /var/www/html/b.txt
php -w /var/www/html/b.txt|sudo tee /var/www/html/b.txt
sudo sed -i 's/  //g' /var/www/html/b.txt
sudo sed -i 's/ </</g' /var/www/html/b.txt
sudo sed -i 's/< /</g' /var/www/html/b.txt
sudo sed -i 's/ ?/?/g' /var/www/html/b.txt
sudo sed -i 's/? /?/g' /var/www/html/b.txt
sudo sed -i 's/ \$/$/g' /var/www/html/b.txt
sudo sed -i 's/$ /$/g' /var/www/html/b.txt
sudo sed -i 's/ =/=/g' /var/www/html/b.txt
sudo sed -i 's/= /=/g' /var/www/html/b.txt
sudo sed -i 's/ \[/[/g' /var/www/html/b.txt
sudo sed -i 's/\[ /[/g' /var/www/html/b.txt
sudo sed -i 's/ ]/]/g' /var/www/html/b.txt
sudo sed -i 's/] /]/g' /var/www/html/b.txt
sudo sed -i 's/ ;/;/g' /var/www/html/b.txt
sudo sed -i 's/; /;/g' /var/www/html/b.txt
sudo sed -i 's/ "/"/g' /var/www/html/b.txt
sudo sed -i 's/" /"/g' /var/www/html/b.txt
sudo sed -i 's/ :/:/g' /var/www/html/b.txt
sudo sed -i 's/: /:/g' /var/www/html/b.txt
sudo sed -i 's/ \//\//g' /var/www/html/b.txt
sudo sed -i 's/\/ /\//g' /var/www/html/b.txt
sudo sed -i 's/ \././g' /var/www/html/b.txt
sudo sed -i 's/\. /./g' /var/www/html/b.txt
sudo sed -i 's/ _/_/g' /var/www/html/b.txt
sudo sed -i 's/_ /_/g' /var/www/html/b.txt
sudo sed -i 's/ (/(/g' /var/www/html/b.txt
sudo sed -i 's/( /(/g' /var/www/html/b.txt
sudo sed -i 's/ )/)/g' /var/www/html/b.txt
sudo sed -i 's/) /)/g' /var/www/html/b.txt
sudo sed -i 's/ ,/,/g' /var/www/html/b.txt
sudo sed -i 's/, /,/g' /var/www/html/b.txt
sudo sed -i 's/ {/{/g' /var/www/html/b.txt
sudo sed -i 's/{ /{/g' /var/www/html/b.txt
sudo sed -i 's/ }/}/g' /var/www/html/b.txt
sudo sed -i 's/} /}/g' /var/www/html/b.txt
sudo sed -i 's/ !/!/g' /var/www/html/b.txt
sudo sed -i 's/! /!/g' /var/www/html/b.txt
sudo sed -i "s/ '/'/g" /var/www/html/b.txt
sudo sed -i "s/' /'/g" /var/www/html/b.txt
sudo sed -i 's/ \\/\\/g' /var/www/html/b.txt
sudo sed -i 's/\\ /\\/g' /var/www/html/b.txt
sudo sed -i 's/ @/@/g' /var/www/html/b.txt
sudo sed -i 's/@ /@/g' /var/www/html/b.txt
sudo sed -i 's/ ^/^/g' /var/www/html/b.txt
sudo sed -i 's/\^ /^/g' /var/www/html/b.txt
sudo sed -i 's/ -/-/g' /var/www/html/b.txt
sudo sed -i 's/- /-/g' /var/www/html/b.txt
sudo sed -i 's/ +/+/g' /var/www/html/b.txt
sudo sed -i 's/+ /+/g' /var/www/html/b.txt
sudo sed -i 's/ \*/*/g' /var/www/html/b.txt
sudo sed -i 's/* /*/g' /var/www/html/b.txt
sudo sed -i 's/ |/|/g' /var/www/html/b.txt
sudo sed -i 's/| /|/g' /var/www/html/b.txt
sudo sed -i 's/ &/\&/g' /var/www/html/b.txt
sudo sed -i 's/& /\&/g' /var/www/html/b.txt
sudo sed -i 's/ >/>/g' /var/www/html/b.txt
sudo sed -i 's/> />/g' /var/www/html/b.txt
sudo sed -i 's/ #/#/g' /var/www/html/b.txt
sudo sed -i 's/# /#/g' /var/www/html/b.txt
sudo sed -i ':a;N;s/\n//;ta' /var/www/html/b.txt
sudo sed -i 's/?php/?php /' /var/www/html/b.txt
sudo sed -i 's/""))/" "))/' /var/www/html/b.txt
sudo sed -i 's/"n/" n/' /var/www/html/b.txt
sudo sed -i 's/"v/" v/' /var/www/html/b.txt
